### ISSUE TITLE
setLibPath fails in Rstudio with Error in x[, 1]

### ISSUE THREAD

**Issue by piccolbo** [RevolutionAnalytics/checkpoint#113]
apparently only when run the first time. Error seems to occur in Rstudio specific code.

The error message is

```
Error in x[, 1] : incorrect number of dimensions
```

**Comment by andrie** [comment]
I now see this in Windows too.  I have added another comment in the RStudio support forum.

**Comment by andrie** [comment]
I have traced the error in the RStudio code and logged a detail report as an amendment to @piccolbo's report.

See https://support.rstudio.com/hc/communities/public/questions/203052576-setting-libpath-in-Rstudio

The actual RStudio code is at https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/SessionPackages.R#L265

**Comment by andrie** [comment]
The temporary workaround is a bit of a dirty hack. The code checks for:

* is Rstudio running?
* is there an exact match of the function `.rs.listInstalledPackages` with a previously known buggy version?

If both conditions are true, then register a new version of `.rs.listInstalledPackages`
