### ISSUE TITLE
Add a check for the appropriate R version

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#140]
Add a function to allow the user to check the current R version, and throw an error if not. Use cases:

* I write a script with R 3.1.1. I want to declare that my script was written with R 3.1.1 so that if I try to run it at a future date, I will know which version of R I must use to replicate results.
* If R gets upgraded "behind the scenes", a script running in production will throw an error. (Better than getting incorrect results.)
* If I share a script with a colleague, they will know which version of R to use to replicate the results (and throw an error otherwise)

Suggested implementation:

```r
check-Rversion("3.1.1") # throw an error if R is not 3.1.1, continue silently otherwise
checkpoint("2014-09-17") # install necessary packages, with versions as of Sep 17 2014
```

**Comment by andrie** [comment]
Implemented using the suggestion by @piccolbo , i.e. `checkpoint..., R.version, ...)`
