### ISSUE TITLE
checkpoint() fails when encountering library(checkpoint)

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/checkpoint#143]
To reproduce, create a file (and save the file) in a clean project containing this code:

```r
library(checkpoint)
checkpoint("2014-09-17")

require(stats)
plot(cars)
```

Then run the code in this file.  The result:

```
Restarting R session...

Revolution R Enterprise version 7.3 (64-bit): an enhanced distribution of R
Revolution Analytics packages Copyright (C) 2014 Revolution Analytics, Inc.

Type 'revo()' to visit www.revolutionanalytics.com for the latest
Revolution R news, 'forum()' for the community forum, or 'readme()'
for release notes.

> source('~/checkpoint-demo/9-checkpoint-errror.R', echo=TRUE)

> library(checkpoint)

checkpoint: Part of the Reproducible R Toolkit from Revolution Analytics
http://projects.revolutionanalytics.com/rrt/

> checkpoint("2014-09-17")
Scanning for loaded pkgs
Scanning for packages used in this project
Installing packages used in this project 
Warning: packages ‘checkpoint’, ‘checkpoint’, ‘stats’ are in use and will not be installed
Error in detach(x, unload = TRUE, force = TRUE) : invalid 'name' argument
> 
```

**Comment by andrie** [comment]
For information: on Windows, these packages are all in the same folder:

Run:

```R
base <- installed.packages(priority = "base")[, "Package"]
sapply(base, function(x){ normalizePath(dirname(system.file(package=x)), winslash = "/") })
```

I get:

```
                                base 
"C:/Program Files/R/R-3.1.2/library" 
                            compiler 
"C:/Program Files/R/R-3.1.2/library" 
                            datasets 
"C:/Program Files/R/R-3.1.2/library" 
                            graphics 
"C:/Program Files/R/R-3.1.2/library" 
                           grDevices 
"C:/Program Files/R/R-3.1.2/library" 
                                grid 
"C:/Program Files/R/R-3.1.2/library" 
                             methods 
"C:/Program Files/R/R-3.1.2/library" 
                            parallel 
"C:/Program Files/R/R-3.1.2/library" 
                             splines 
"C:/Program Files/R/R-3.1.2/library" 
                               stats 
"C:/Program Files/R/R-3.1.2/library" 
                              stats4 
"C:/Program Files/R/R-3.1.2/library" 
                               tcltk 
"C:/Program Files/R/R-3.1.2/library" 
                               tools 
"C:/Program Files/R/R-3.1.2/library" 
                               utils 
"C:/Program Files/R/R-3.1.2/library" 
```

**Comment by andrie** [comment]
I have a possible solution to this.

The full library path should consist of:

1. The `checkpoint` path, i.e. containing all the project libraries
2. The R system library path, i.e. containing the R system libraries, e.g. `stats`, `compiler`, etc.

The R object `.Library` contains the path to the R system libraries.

Hence my proposal is to change the function `checkpoint:::setLibPaths` to 

```r
setLibPaths <- function(snapshotDate, libPath=checkpointPath(snapshotDate, "lib")){
  assign(".lib.loc", c(libPath, .Library), envir = environment(.libPaths))}
```

I have run the tests in Windows and all tests pass.

**Comment by piccolbo** [comment]
Unfortunately that path contains lots of other packages (in my case, all that I ever installed on this version of R). If you include it, user can and will use a mix of checkpointed and current packages.

**Comment by andrie** [comment]
Good point. I use my libraries differently, so didn't consider this use case.

However, maybe this doesn't matter?

What I mean is this:  all packages under `checkpoint` control should be found in the `checkpoint` folder.  Then the `.Library` folder will only be used for base packages, i.e. packages explicitly not under `checkpoint` control.

It's a bit messy - and assumes that we are absolutely correct in both design and implementation, but could work?

**Comment by piccolbo** [comment]
The library loading happens in `library`. We can't add or change anything in that function.

**Comment by andrie** [comment]
I think we implicitly can, since `library()` takes an argument `lib.loc` that defaults to `.libPaths()`

Thus by setting `.libPaths()` as we do by setting `.lib.loc` we are implicitly changing where `library()` looks for packages.

So I'm probably missing some nuance in your meaning.

**Comment by piccolbo** [comment]
It's not really that nuanced. Checkpoint works because we are segregating packages by date. If we don't it doesn't. So they are segregated on MRAN and they are as well on the local machine. If you include the date-specific directory and some other directory in the .libpaths, we can tweak their order so that it will load preferentially, but not exclusively, checkpointed packages. As it is now, if you are checkpointed and you call library(some-package) and you don't have it installed from the appropriate snapshot, it will fail. If we add the system library on the libpaths, when you call library(some-package) it will not fail if it had been installed before in the system library, independent of date or snapshot. That's a much weaker guarantee.  Add to that that this problems doesn't affect any of the base packages other than compiler,

```
> checkpoint("2015-01-02")
Scanning for loaded pkgs
Scanning for packages used in this project
No packages found to install
NULL
> library(compiler)
Error in library(compiler) : there is no package called ‘compiler’
> library(datasets)
> search
function () 
.Internal(search())
<bytecode: 0x7ff88b12eeb0>
<environment: namespace:base>
> search()
 [1] ".GlobalEnv"         "package:checkpoint" "package:stats"     
 [4] "package:graphics"   "package:grDevices"  "package:utils"     
 [7] "package:datasets"   "package:methods"    "Autoloads"         
[10] "package:base"      
> library(parallel)
> library(splines)
> library(stats4)
> 
```
and you see why this bug was closed as it was. If @stefanfritsch has a candidate solution, absolutely we will look into it, but as it is I am not going to break everything for this one single package. Otherwise the workaround is to load compiler before checkpointing. Sorry but that will have to do.

**Comment by piccolbo** [comment]
Wait a second I may have an idea for a solution. Hold your breath (metaphorically).

**Comment by revodavid** [comment]
We may be overthinking this. The intent is that *every* time:

checkpoint(<date>)

is called, it checks that the local package directory and makes sure that
all necessary packages are installed from the snapshot (and installs them
if not).

Thenceforth, all correct package versions should be found first on the
search path when library() is called.

# David

-- 
David M Smith <david@revolutionanalytics.com>
Chief Community Officer, Revolution Analytics
http://blog.revolutionanalytics.com
Tel: +1 (650) 646-9523 (Chicago IL, USA)
Twitter: @revodavid


On Fri, Jan 9, 2015 at 10:55 AM, Antonio Piccolboni <
notifications@github.com> wrote:

> It's not really that nuanced. Checkpoint works because we are segregating
> packages by date. If we don't it doesn't. So they are segregated on MRAN
> and they are as well on the local machine. If you include the date-specific
> directory and some other directory in the .libpaths, we can tweak their
> order so that it will load preferentially, but not exclusively,
> checkpointed packages. As it is now, if you are checkpointed and you call
> library(some-package) and you don't have it installed from the appropriate
> snapshot, it will fail. If we add the system library on the libpaths, when
> you call library(some-package) it will not fail if it had been installed
> before in the system library, independent of date or snapshot. That's a
> much weaker guarantee. Add to that that this problems doesn't affect any of
> the base packages other than compiler,
>
> > checkpoint("2015-01-02")
> Scanning for loaded pkgs
> Scanning for packages used in this project
> No packages found to install
> NULL
> > library(compiler)
> Error in library(compiler) : there is no package called ‘compiler’
> > library(datasets)
> > search
> function ()
> .Internal(search())
> <bytecode: 0x7ff88b12eeb0>
> <environment: namespace:base>
> > search()
>  [1] ".GlobalEnv"         "package:checkpoint" "package:stats"
>  [4] "package:graphics"   "package:grDevices"  "package:utils"
>  [7] "package:datasets"   "package:methods"    "Autoloads"
> [10] "package:base"
> > library(parallel)
> > library(splines)
> > library(stats4)
> >
>
> and you see why this bug was closed as it was. If @stefanfritsch
> <https://github.com/stefanfritsch> has a candidate solution, absolutely
> we will look into it, but as it is I am not going to break everything for
> this one single package. Otherwise the workaround is to load compiler
> before checkpointing. Sorry but that will have to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RevolutionAnalytics/checkpoint/issues/143#issuecomment-69362707>
> .
>

-- 
 

Revolution R Plus <http://revolutionanalytics.com/plus>

Subscribe to Technical Support & Indemnification for R

**Comment by piccolbo** [comment]
Works for me. Please @andrie and @stefanfritsch take it for a spin and let me know. Will reopen if necessary

**Comment by andrie** [comment]
Does not work on Windows.  I am working on a fix.

**Comment by andrie** [comment]
My last commit adds unit tests to actually load the required packages.  This causes the tests to fail.  I think this happens because the package unload / reload sequence in `checkpoint.R` is incorrect.

The error occurs in this code:

```r
# detach and reload checkpointed pkgs already loaded
  search.path = search()
  lapply(
    unlist(
      lapply(
        packages.to.install,
        grep,
        x = search.path)),
    function(x) {
      detach(x, unload = TRUE, force = TRUE)
      library(search.path[x], character.only = TRUE)})
```

I am investigating.

**Comment by andrie** [comment]
The underlying problem was:

* The package unloading occurred *after* the installation of packages.  This meant that package installation failed.
* In addition, on `detach()` the search order changes since the detached package drops out from the search path, and the index numbers get updated.


The fix consists of:

* Moving the detach sequence earlier, before the package installation happens.
* Using a different `detach` algorithm, where packages get detached individually, then re-querying the search path.  In addition, allow for the fact that some packages will not detach, since they are required by other loaded packages.  Thus repeat the process several times.

Replaced that code with the following:

```r
  # detach checkpointed pkgs already loaded
  
  local({
    findInSearchPath <- function(p){
      g <- grep(sprintf("package:%s$", paste(p, collapse="|")), search())
      if(length(g)) min(g) else character(0)
    }
    
    p <- packages.to.install
    max.n <- 10 * length(p) # Prevent endless loop as a failsafe
    n <- 0
    repeat {
      d <- findInSearchPath(p)
      if(length(d) == 0) break # Stop if all packages unloaded
      try(
        detach(pos = d, unload = TRUE, force = TRUE),
        silent = TRUE
      )
      n <- n + 1
      if(n > max.n) break
    }
  })
```

**Comment by andrie** [comment]
@piccolbo An important side-effect of my last commit is that I don't reload packages after unloading them.  I think this is ok, since the packages will get loaded by the `checkpoint` script.

To be precise: whenever the code encounters `checkpoint(...)` all checkpointed packages get unloaded.

Can you think of a use case where this is going to be problematic?

**Comment by piccolbo** [comment]
Yes, I think there are different use cases one of which doesn't involve a script, packages are loaded interactively then checkpoint is used. There is no reason to surprise the user by detaching currently loaded packages. Plus your code is long and complicated, I don't even understand it. The order of operations you want is the correct one. Let's change just that.

**Comment by andrie** [comment]
I couldn't find an adaptation of your code to pass the unit tests, and my version is the simplest I could create.

The reason the original code fails is:

1. The order or unloading the loaded packages matters.
2. You can't perform a single `grep()` followed by multiple `detach()` because each `detach()` changes the search order.

The "complicated" bit in my code is that I don't know ex-ante how many passes to make through the search path to unload all the packages, hence the `repeat` with a counter up to a pre-set maximum that's hopefully large enough.

**Comment by piccolbo** [comment]
I get your code now. detach needs a recursive option, but that's for
another day. Can you at least reload the packages?

**Comment by andrie** [comment]
OK, I shall add that in the morning. We can then test and hopefully close this issue.

I have some remaining doubts about the reloading order of the packages - I don't think it's possible to retain the search order, for example.  I'll open a separate issue to discuss this.

**Comment by piccolbo** [comment]
While it's not an unreasonable concern, it's one or two levels lower
priority IMHO (not so many things rely on search order). I agree with
reloading in any order, closing this issue documenting the fact. If you
want to open a new issue, sure, but I'd wait until there is one use case
that shows it's worth it.

**Comment by andrie** [comment]
I have added this code (modified to only load packages found in the search path).

All tests pass on my machine.  If you can confirm the same, then I propose we close the issue.

**Comment by piccolbo** [comment]
It's a bug fix, you need to work in master.

**Comment by piccolbo** [comment]
looks good otherwise. You need to cherry pick into master all the above commits.  I can do it if you are sure you pushed everything that you wanted in for this bug. Cherry pick should always be plan B, it's better to pick the right branch in the first place. If you are uncomfortable working in master because the fix is complex, you can use a bug fix branch off master. Not common  but perfectly fine.
