### ISSUE TITLE
Using checkpoint with R Server (MRS)

### ISSUE THREAD

**Issue by QuantDevHacks** [RevolutionAnalytics/checkpoint#146]
Working directory set to the default ("My Documents") on Win7-64, which has a lot of files and directories.

Entered:
checkpoint("2014-10-10")

Seemed to parse through OK until the end, when I got:

```
Error in detach(x, unload = TRUE, force = TRUE) : invalid 'name' argument
In addition: Warning messages:
1: In value[[3L]](cond) :
  Failed to parse C:/Users/dan.hanson/Documents/Documents/Documents/hadoop_alpha.R ; dependencies in this file will not be discovered.
2: In value[[3L]](cond) :
  Failed to parse C:/Users/dan.hanson/Documents/Documents/Documents/stuff.R ; dependencies in this file will not be discovered.
3: In value[[3L]](cond) :
  Failed to parse C:/Users/dan.hanson/Documents/InstallFiles/Revolution/LixinBuilds/RevoScaleR/demoScripts/RevoScaleR_Users_Guide.R ; dependencies in this file will not be discovered.
4: packages ‘doRSR’, ‘quantstrat’, ‘PortfolioAnalytics’ are not available (for R version 3.1.1) 
```

Please note that RRE 7.3. uses R v3.1.1

**Comment by Hong-Revo** [comment]
You can now work with non-CRAN packages in checkpoint v1.0, via the `checkpoint.yml` manifest file:

- For packages that are publicly available on Bioconductor or Github, add these in the `refs:` line
- For packages that you want to continue using but are NOT public (eg Revo-distributed stuff), add them to the `exclude:` line, and specify `prepend=TRUE` in your `checkpoint()` call

See `?checkpoint` for more information.
