### ISSUE TITLE
Add checkpoint package to the ReproducibleResearch task view

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#147]
Should be listed in http://mran.revolutionanalytics.com/taskview/info/?ReproducibleResearch

**Comment by andrie** [comment]
I wrote to Max on Nov 15, 2014 and again on Jan 10, 2015.  Awaiting response.

**Comment by andrie** [comment]
Closing, since `checkpoint` is mentioned at https://cran.r-project.org/web/views/ReproducibleResearch.html
