### ISSUE TITLE
Give the user visual feedback while checkpoint() is processing

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#149]
If you call the checkpoint function in a folder with many .R files, it can take a long time to scan files and install the required packages. Give the user visual feedback as the checkpoint function processes. Indicate the files that are being scanned and packages that are being installed. For example:

Scanning twitter-graph.R ... requires packages twitteR igraph and 22 dependencies
Scanning simulation.R ... no dependent packages
Scanning ml_demo.R ... requires packages rpart MASS e1071 and 15 dependencies
Installing required packages and dependencies from 2014-11-12 snapshot:
Installing profileModel ... successful
Installing colorspace ... successful
Installing gtable ... FAILED (package not found in snapshot)
These base and recommended packages will be sourced from the R installation: parallel utils splines

Make sure to flush stdout after every message so the user can see continuous progress.
Add an option silent=TRUE (default FALSE) to suppress these messages.

Remove the warning about base/recommended package dependencies.

**Comment by andrie** [comment]
This has now been included in https://github.com/RevolutionAnalytics/checkpoint/releases/tag/0.3.6
