### ISSUE TITLE
CRAN package dependencies change over time, so unit test can not refer to fixed set

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/checkpoint#152]
In the unit tests we manually test for a set of expected packages and their dependencies.  In the tests, we hand-pick and hand-calculate the expected dependencies.

However, in time, the packages on CRAN can change, and the tests start to fail as time (the snapshot date) passes.

**Comment by piccolbo** [comment]
How about

```
unique(unlist(sapply(packages.to.test, package_dependencies, db = available.packages())))
```

**Comment by andrie** [comment]
Yes, something along those lines.  It's a little bit more complicated because we have to do a setdiff() to exclude base packages.

I have working code and will push shortly.

**Comment by piccolbo** [comment]
Remember than now compiler gets installed in the checkpointed library, so
it may seem it's checkpointed even if it's not.
