### ISSUE TITLE
Error when checkpoint installs packages (harmless)?

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#158]
Every time I run a script that requires packages to get installed I see this error:

```
Error in x[, 1] : incorrect number of dimensions
```

The error doesn't appear to cause any problems though, and everything installs and runs fine.
In context:

```
> source('~/R/weather/weather.R')

checkpoint: Part of the Reproducible R Toolkit from Revolution Analytics
http://projects.revolutionanalytics.com/rrt/
Loading required package: knitr
* installing *binary* package ‘compiler’ ...
* DONE (compiler)
Error in x[, 1] : incorrect number of dimensions
Scanning for loaded pkgs
...
```

The error does not occur in the second run-though when the required packages are already installed in the .checkpoint folder:

```
> source('~/R/weather/weather.R')
* installing *binary* package ‘compiler’ ...
* DONE (compiler)
Scanning for loaded pkgs
Scanning for packages used in this project
All detected packages already installed
checkpoint process complete
---
```

**Comment by andrie** [comment]
This is most likely not a `checkpoint` error, but an RRO installation error.

**Comment by revodavid** [comment]
Actually, I think it's an RStudio error. The error appears when running the code in RStudio, but not when running from the Terminal (output after deleting `.checkpoint`)

```
> source("weather.R")

checkpoint: Part of the Reproducible R Toolkit from Revolution Analytics
http://projects.revolutionanalytics.com/rrt/
Loading required package: knitr
* installing *binary* package ‘compiler’ ...
* DONE (compiler)
Scanning for loaded pkgs
Scanning for packages used in this project
Installing packages used in this project 
 - Installing ‘dplyr’
...
```

**Comment by andrie** [comment]
ah. ok.  That's helpful.  I know how to fix this.  Stand by.

**Comment by andrie** [comment]
The solution is to import `utils` in the NAMESPACE, so `install.packages()` calls `utils` rather than being masked by RStudio
