### ISSUE TITLE
Error in x[, 1] : incorrect number of dimensions

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/checkpoint#165]
On occasion, `checkpoint()` prints the following message upon completion:

```
Error in x[, 1] : incorrect number of dimensions
```

This doesn't seem like a real error, but an error that is trapped somewhere and displayed in the message stream instead.

**Comment by revodavid** [comment]
I used to see this running checkpoint in RStudio, but no longer see it in 0.3.7.

**Comment by andrie** [comment]
Somehow it's back, but only under certain conditions.  there is some odd interaction with RStudio replacement functions in the `tools:rstudio` environment, but it's proving hard to isolate.

I found it first on Ubuntu, but can now replicate in Windows too.

**Comment by andrie** [comment]
After much work, I realised two things:

1. This happens in an RStudio replacement function
2. Antonio discovered and reported this problem ages ago

Closing as duplicate of #113
