### ISSUE TITLE
Include direct namespace calls with ```::``` or ```:::``` into scan for packages

### ISSUE THREAD

**Issue by Philipp-Neubauer** [RevolutionAnalytics/checkpoint#166]
Currently ```::``` and `:::` calls to package namespaces do not seem to be included in the snapshot list (or at least the behaviour isn't documented)

**Comment by andrie** [comment]
Correct.  This is not current behaviour.

Can you please describe a use case where it makes sense to use `package::function()` **without** calling `library("package")` at the top of your script?

(I understand that `package::function()` can allow you to avoid namespace masking, but that doesn't seem like a good reason to not write `library()` at the top of your script.  However, I'm not keen to include additional complexity into the package without understanding the use case better.)

**Comment by andrie** [comment]
Some discussion about avoiding namespace pollution by using `package::function()` instead of `library("package")` at 

http://yihui.name/en/2014/07/library-vs-require/

**Comment by piccolbo** [comment]
One use case is with optional (suggests:) dependencies. If one uses library
in a package R CMD check will issue warnings about it. The recommended way
 to use suggest packages is to check they are present with requireNamespace
and then use the fully qualified name. I am not sure we've ever thought
about using checkpoint inside packages, maybe we should.

**Comment by andrie** [comment]
I think it's easy to add `requireNamespace` to the list of tokens we search for (in addition to `library` and `require`.

**Comment by piccolbo** [comment]
Good point. By the way, what do lines 172-175 scanRepoPackages.R file, dev
branch do?

```
 # base case: call to :: or :::
    if (fname %in% c("::", ":::")) (
      return(as.character(e[[2L]]))
    )
```

**Comment by andrie** [comment]
Good question.  I'll run some tests.  At first glance it looks like it answers the original request.

**Comment by Philipp-Neubauer** [comment]
My use-case is not within a package (in general, although sometimes I'll
use the suggests in a packaged project as well) - I often use the
```package::function()``` calls in larger projects where I don't want
loaded packages from one script to induce some undesired or unforeseen
behaviour in another. For example, reshape, reshape2 and tidyr all have
similar functions, but depending on my thinking at a particular point in
time I'll use one over another. But I don't want any of those name-spaces
to be loaded by default. Similar things go for plyr, which does (or at
elast used to) conflict with dplyr, so I'd simply use
```plyr::function()``` if I wanted that behaviour (although that happens
less as dplyr progresses). But I guess that I could use a
```equireNamespace``` to explicitly state which namespaces I want to be
available.

On Wed, Feb 11, 2015 at 8:23 AM, Antonio Piccolboni <
notifications@github.com> wrote:

> Good point. By the way, what do lines 172-175 scanRepoPackages.R file, dev
> branch do?
>
> ```
> # base case: call to :: or :::
> if (fname %in% c("::", ":::")) (
> return(as.character(e[[2L]]))
> )
> ```
>
> On Tue, Feb 10, 2015 at 10:09 AM, Andrie de Vries <
> notifications@github.com>
> wrote:
>
> > I think it's easy to add requireNamespace to the list of tokens we search
> > for (in addition to library and require.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/RevolutionAnalytics/checkpoint/issues/166#issuecomment-73750749
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RevolutionAnalytics/checkpoint/issues/166#issuecomment-73764928>
> .
>



-- 
Phil

**Comment by andrie** [comment]
@piccolbo the code you ask about didn't work as expected.  It correctly identifies `::` and `:::` but then returns an inappropriate value.

The correct incantation is:

```r
    # base case: call to :: or :::
    if (fname[1] %in% c("::", ":::")) (
      return(as.character(fname[2]))
    )
```

I am running some more tests but will push a fix soon.
