### ISSUE TITLE
Allow users to select local package library

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#167]
checkpoint installs packages in  ~/.checkpoint/DATE, but users would like to be able to customize where packages are installed and found. (Use case: running R or R scripts from a USB stick.)

See thread at https://groups.google.com/d/msg/rropen/iKugI_iRnqg/wujJbbANfqgJ

**Comment by andrie** [comment]
Proposal: add a new argument to `checkpointLocation` that the user can modify

```r
checkpoint(..., checkpointLocation = "~/.checkpoint")
```

**Comment by pcavatore** [comment]
looks great

**Comment by andrie** [comment]
On reflection, the usage should be:

```r
checkpoint(..., checkpointLocation = "~/")
```

This will create the library in `~/.checkpoint`

**Comment by pcavatore** [comment]
makes sense

**Comment by andrie** [comment]
@pcavatore This fix is now available in the dev branch on github.  Can you please install and tell me if you find anything unusual / not working?

```r
devtools::install_github("RevolutionAnalytics/checkpoint", ref = "dev")
```

**Comment by pcavatore** [comment]
it works fine...as an aside note checkpointLocation = "~/.checkpoint" would give the extra option to choose a different folder other than .checkpoint but I understand this could generate some troubles and it's really a minor point.
