### ISSUE TITLE
Create mechanism to specify packages to install

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/checkpoint#168]
In #162 @Philipp-Neubauer requested:

> May I suggest one more level of flexibility - i.e., rather than just a `scanForPackages`, have a packages option with default `checkpoint(..., packages = all)` which leads to the default scan behaviour, and options to specify a vector of package names to manually dictate the package list or say packages = none for the behaviour suggested above.

This request was slightly ambiguous, and unresolved.

In essence, the use case seems to be:

* Allow the user to specify a list of packages to install

Proposal: we can achieve this with an option like:

```r
checkpoint(..., packages = "...")
```

where `packages` can possibly be a vector or a file containing a manifest of sorts.

**Comment by piccolbo** [comment]
I think the part of the issue that you moved here had been resolved in the sense that 
```
checkpoint(..., scan = FALSE)
install.packages(list-of-pkgs)
```
was proposed as a valid  alternative and the user had conceded that to the best of my understanding. Otherwise, by the same token,  for any two calls A(...) followed by B(...) we could implement A(..., do.also.B = TRUE, B.args = ...) which if it passes management muster would guarantee our employment until the end of time, but would not fit my ideals of minimalist programming

**Comment by Philipp-Neubauer** [comment]
I agree that parsimony in programming is a desirable feature, and yes, by
your logic there are endless possibilities of combining statements and
employment opportunities galore, but isn't that the case in general? E.g.,
any function etc is just that - a convenient wrapper of some functionality
into a single call to make the code more parsimonious and readable. Any
code could be re-written in a way that did not involve any functions,
libraries etc. Of course that's the extreme end of it, but convenience
sometime trumps minimalism, and in some cases it makes sense two combine
statements into some wrapper, and in other cases it doesn't. I'm not
implying that this is a case where it makes sense, just enjoying this
little digression :)

My two cents - that are not to say that I don't agree that the above isn't
fine and workable.

On Thu, Feb 12, 2015 at 10:15 AM, Antonio Piccolboni <
notifications@github.com> wrote:

> I think the part of the issue that you moved here had been resolved in the
> sense that
>
> checkpoint(..., scan = FALSE)
> install.packages(list-of-pkgs)
>
> was proposed as a valid alternative and the user had conceded that to the
> best of my understanding. Otherwise, by the same token, for any two calls
> A(...) followed by B(...) we could implement A(..., do.also.B = TRUE,
> B.args = ...) which if it passes management muster would guarantee our
> employment until the end of time, but would not fit my ideals of minimalist
> programming
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RevolutionAnalytics/checkpoint/issues/168#issuecomment-73966292>
> .
>



-- 
Phil

**Comment by andrie** [comment]
OK. Proposing to not fix this.
