### ISSUE TITLE
checkpoint errors without a network connection

### ISSUE THREAD

**Issue by bpbond** [RevolutionAnalytics/checkpoint#171]
Checkpoint errors if there's no Internet connection available, even if all packages are already installed:

```
> checkpoint("2015-02-27")
Error in value[[3L]](cond) : 
  Unable to reach MRAN: cannot open the connection
```

Is this correct behavior? That is, since all packages for this checkpoint date are already installed (see below**), and this can be verified, why does this error occur? This is my first time using the package, and apologies if I'm misunderstanding its functionality.

** with a network connection:

```
> checkpoint("2015-02-27")
Scanning for packages used in this project
  |==============================================================================| 100%
- Discovered 3 packages
All detected packages already installed
checkpoint process complete
---
```

**Comment by piccolbo** [comment]
Makes sense to me that the error should happen only at the first package install.

**Comment by nilesh1984** [comment]
I am getting this error even if when I am connected to a network. Packages are installing from MRAN but checkpoint package is showing an error.

**Comment by andrie** [comment]
@nilesh1984 What version of `checkpoint` are you using?

**Comment by nilesh1984** [comment]
package 0.3.9 on ubuntu 14.04 LTS and using RRO 8.0.3

**Comment by andrie** [comment]
We added an experimental fix in `checkpoint` version 0.3.10.

Can you please update `checkpoint` and try again?

**Comment by nilesh1984** [comment]
the problem is that rro 8.0.3 takes a default date version to 1st April.
since I cannot change the default date, I cannot update the package. the
only way I think this problem can be solved is by updating rro to a newer
version.

on a secondary note, I think that the default date for rro should be set to
the current date instead of a back date. in such a case if the checkpoint
package develops an error, we will be able to update it to a newer version.

**Comment by andrie** [comment]
You can install packages from a current version of CRAN, or any MRAN snapshot


Try this:

```r
install.packages("checkpoint", repos = c(CRAN = "cran.revolutionanalytics.com"))
```

to update `checkpoint` to the current version on CRAN.

This is described in the FAQ at https://mran.revolutionanalytics.com/faq/#change-repos

**Comment by nilesh1984** [comment]
I ran the commands as you told me .  Installed checkpoint from a different
repo. Then I ran checkpoint again. I am getting a familiar error at the end

this is the output of the command checkpoint("2014-07-12")

Scanning for packages used in this project

|===========================================================================================================|
100%
- Discovered 240 packages
Unable to parse 67 files:
-
R/x86_64-unknown-linux-gnu-library/R-3.1.2/checkpoint/examples/example_checkpoint.R
-
R/x86_64-unknown-linux-gnu-library/R-3.1.2/checkpoint/examples/example_setSnapshot.R
-
R/x86_64-unknown-linux-gnu-library/R-3.1.2/deSolve/doc/examples/Daphnia_event.R
-  and many other such files
.....
Warning: unable to access index for repository
http://mran.revolutionanalytics.com/snapshot/2014-07-12/src/contrib
Packages not available in repository and won't be installed:
 - abind
 - acepack
 - actuar
 - AER
 - agridat
 - akima
.... and many other packages
 Zelig
 - ZeligCommon
 - zoo
All detected packages already installed
checkpoint process complete
---
Warning messages:




*1: In value[[3L]](cond) : Unable to reach MRAN: cannot open the
connection2: In value[[3L]](cond) : Unable to find snapshot on MRAN3: In
projectScanPackages(project, use.knitr = use.knitr) :  rmarkdown files
found and will not be parsed. Set use.knitr = TRUE*


The woods are lovely, dark and deep
But I have promises to keep
And miles to go before I sleep
And miles to go before I sleep
-----

**Comment by andrie** [comment]
Thank you for the additional information.

One problem is that you are pointing to a non-existent snapshot date (2014-07-12). The earliest available snapshot is "2014-09-17". This explains one of the errors, although I am surprised that checkpoint doesn't then stop executing.

This leads me to think that you possibly still don't have the latest version.

Please open a clean session of R, then tell me the results of:

```r
library("checkpoint")
sessionInfo()
```

**Comment by nilesh1984** [comment]
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_IN.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_IN.UTF-8        LC_COLLATE=en_IN.UTF-8
 [5] LC_MONETARY=en_IN.UTF-8    LC_MESSAGES=en_IN.UTF-8
 [7] LC_PAPER=en_IN.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_IN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods
[7] base

other attached packages:
[1] checkpoint_0.3.10

loaded via a namespace (and not attached):
[1] tools_3.1.3


The woods are lovely, dark and deep
But I have promises to keep
And miles to go before I sleep
And miles to go before I sleep
-----

**Comment by andrie** [comment]
Thank you.

Now, let me go back and understand what your problem is.

This thread started by reporting an error when there is no network connection.  We fixed this in `checkpoint` v0.3.10.

You report that you have the same error.  I then suggested you upgrade to the latest version, which you did.

But reading your latest report again, it seems to me that the problem has been resolved.  `checkpoint` no longer throws an error, but completes successfully - this time with a warning that you have no connection.

This seems like desirable behaviour to me?  Do you agree?

**Comment by nilesh1984** [comment]
Yes this would be an admirable summary. I cannot understand if it is
downloading the packages or not.


Just to add to these, I ran checkpoint with the following date 2015-07-01
for which I hope a snapshot exists

and then it did the following

Scanning for packages used in this project
  |============================================================| 100%
- Discovered 8 packages
Installing packages used in this project
 - Installing ‘broom’
also installing the dependencies ‘assertthat’, ‘R6’, ‘magrittr’,
‘lazyeval’, ‘DBI’, ‘BH’, ‘reshape2’, ‘stringi’, ‘mnormt’, ‘plyr’, ‘dplyr’,
‘tidyr’, ‘psych’, ‘stringr’

 - Installing ‘data.table’
also installing the dependency ‘chron’

.... and then ended with the same warning Like this

 - Previously installed ‘tidyr’
 - Installing ‘zoo’
checkpoint process complete
---
Warning message:
In value[[3L]](cond) : Unable to reach MRAN: cannot open the connection



On Fri, Jul 24, 2015 at 4:15 PM, Andrie de Vries <notifications@github.com>
wrote:

> This seems like desirable behaviour to me? Do you agree?
>
>


The woods are lovely, dark and deep
But I have promises to keep
And miles to go before I sleep
And miles to go before I sleep
-----

**Comment by andrie** [comment]
This no longer throws an error, but just a warning.

**Comment by bpbond** [comment]
Thanks for changing this behavior.
