### ISSUE TITLE
create checkpoint epoch error message

### ISSUE THREAD

**Issue by cmosetick** [RevolutionAnalytics/checkpoint#174]
If a user selects a date in checkpoint before snapshots existed, the error message returned is less then helpful clarifying the situation:

```
> checkpoint("2013-10-29")
Error in value[[3L]](cond) : Unable to find snapshot on MRAN
```

Instead, propose to let users know that the date they selected is before the `checkpoint-server` epoch for snapshots via a more intuitive error message:

```
Selected date is before the checkpoint-server epoch.
Please select a snapshot that is after 2014-09-17.
```

**Comment by piccolbo** [comment]
That's the problem in this case, but it's not an accurate message for that
exception in general. Your message is an improvement only if limited to the
specific condition, not as a replacement. There's also future dates to take
into account if perfection is the goal.

**Comment by revodavid** [comment]
Replaced by #182

**Comment by andrie** [comment]
Whoever finds time to design and implement this, please consider my original suggestion in #89 where I suggested a simple API consisting of an .rds file that contains the dates of all valid snapshots. This (to me) seems more elegant than a client-driven brute force search through the folder structures, and not difficult to implement.
