### ISSUE TITLE
Support BioConductor packages

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#179]
Detect BioConductor packages used in a process, and have `checkpoint` install the versions of those packages as they existed on the checkpoint date.

**Comment by kforner** [comment]
As I understand, bioconductor packages are already versioned on a release (~ 6 months) basis. 
So far I guess that the MRAN repositories do not include bioc packages. 
But check-pointing the BioC version might be enough, or at least a start.
For instance, here's how I used to control my packages: MRAN snapshot + bioc version
```
options(repos = c(
    CRAN = "http://mran.revolutionanalytics.com/snapshot/2014-09-19/",
    BioCsoft = "http://bioconductor.statistik.tu-dortmund.de/packages/3.0/bioc",
    BioCann = "http://bioconductor.statistik.tu-dortmund.de/packages/3.0/data/annotation",
    BioCexp = "http://bioconductor.statistik.tu-dortmund.de/packages/3.0/data/experiment",
    BioCextra = "http://bioconductor.statistik.tu-dortmund.de/packages/3.0/extra"
))
```

**Comment by andrie** [comment]
@kforner Thank you for your proposal.

I agree with you - this is the easiest way of implementing support for BioConductor.

**Comment by revodavid** [comment]
It would be nice if the checkpoint function added the appropriate BioConductor repos to the repository path, but we'd need a BioConductor expert to veryify how it works with e.g. biocLite.R

**Comment by mtmorgan** [comment]
If the user is following Bioc best practices, then the repositories in use are at `BiocInstaller::biocinstallRepos()` -- the package BiocInstaller determines Bioconductor version through specification of respository.

A problem for exact reproducibility is that `bioinstallRepos()` points to the same repositories throughout the six month release cycle, so if a package goes from version 1.20.0, to 1.20.1 to 1.20.2 during the release, then at the end of the release the repository contains only version 1.20.2; it is not easy to recover 1.20.0 or 1.20.1, but 1.20.2 will be available for a very long time.

Packages in our release branch (even numbered `y` in version `x.y.z`) are supposed only to get updated with bug fixes, leading to a version bump on `z`. So the difference between 1.20.0 and 1.20.2 would be perhaps two bug fixes, at least in principle. It could be much more dramatic in our devel (odd numbered y) branch, where developers are encouraged to implement and test new features.

**Comment by Hong-Revo** [comment]
Now supported (mostly) in checkpoint v1.0, via the `checkpoint.yml` manifest. You can include such packages in the checkpoint, but their versions won't be looked at -- it's still your responsibility to make sure you're using the right versions.
