### ISSUE TITLE
In batch mode, stop() if .checkpoint folder isn't found

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/checkpoint#181]
Following up from #177

In batch mode, it's confusing when the `.checkpoint` folder defaults to `tempdir()`  if the `checkpointLocation` folder doesn't exist.

Desired behaviour:

* Stop by throwing an error
* Print a helpful message that the sys admin should create the appropriate folder

This still complies with CRAN rules, since the tests run in `tempdir()` by setting the `checkpointLocation`

**Comment by piccolbo** [comment]
I'd make it a warning. We  have an option of completing the program correctly using tempdir with the only drawback that the cache would need to be rebuilt the next time. Doesn't build up to a reason to call it quits in my book.

**Comment by revodavid** [comment]
I'm overruling here -- we will make it an error. The reasoning is to alert an administrator of an otherwise unattended system, rather than having a production system download all packages every run, without anyone knowing about it.
