### ISSUE TITLE
If a snapshot doesn't exist, suggest the previous and next available snapshots

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#182]
When the user calls `checkpoint(DATE)` there is a possibility the snapshot won't exist on mran.revolutionanalytics.com/snapshot

* If the user requests a date before 2014-09-08, issue the following error message:

```
Snapshot for DATE note available. Use checkpoint("2014-08-09") for the earliest available snapshot.
```

* If the user requests a date after 2014-09-08, and the folder mran.revolutionanalytics.com/snapshot/DATE does not exists, issue the following message:

```
Snapshot for DATE not available. Use checkpoint(DATE1) for the earlier available snapshot, or checkpoint(DATE2) for the next available snapshot.
```

Calculate DATE1 by searching backwards for existing mran.revolutionanalytics.com/snapshot/DATE folders. Calculate DATE2 by searching backwards for existing mran.revolutionanalytics.com/snapshot/DATE folders, halting at tomorrow's date. If a later snapshot cannot be found, skip the DATE2 part of the message.

Implementation suggestion: we could skip online searches by providing an object with dates we already know not to exist (e.g. 2015-06-04 through 2015-06-08).

**Comment by j-martens** [comment]
As noted in #174 by @andrie:

Whoever finds time to design and implement this, please consider my original suggestion in #89 where I suggested a simple API consisting of an .rds file that contains the dates of all valid snapshots. This (to me) seems more elegant than a client-driven brute force search through the folder structures, and not difficult to implement.

**Comment by j-martens** [comment]
I believe the RRO team would need an updated version of checkpoint package available on CRAN on or before the July 1st date since that is to be our next snapshot date for the RRO 3.2.1 release.

**Comment by piccolbo** [comment]
Given the lack of a distribution mechanism to keep lists of available dates up to date in between releases, independent of ominous sounding names or efficient formats, per today's meeting discussion, we agreed we are going to make the directory  of snapshots officially list-able (it is already, but we now make it a requirement) and read available dates from there on demand.

**Comment by andrie** [comment]
Version 0.3.14 adds this behaviour.

- Automatically add `knitr` and `rmarkdown` packages if `.Rmd` files found #173
- This behaviour is controlled by the `auto.install.knitr` argument (default TRUE)
