### ISSUE TITLE
User-configurable checkpoint-server URL

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#184]
Allow the user to specify a root for the snapshot URL (currently is it hardcoded to: `http://mran.revolutionanalytics.com/snapshot/`. This would allow users to select an alternate snapshot mirror, or to use an HTTPS-enabled mirror.

**Comment by andrie** [comment]
One potential use case is that the user defined "mirrors" may not in fact be mirror copies. This could happen, for example, if an organisation creates a private CRAN using miniCRAN, thay may possibly include github pacages.

For this use case, the promise of reproducibility will fail.

I propose that we don't try to address this.

Reproducibility is only promised if the user exclusively uses http://mran.revolutionanalytics.com or https://mran.revolutionanalytics.com

**Comment by piccolbo** [comment]
+1 on not attacking the mirror issue just yet unless we have a way to check that the mirrors are faithful (hard with something that changes every night) and a compelling need for mirror support. As far http/https, there is an auto-detect type solution in branch https that tries to do the right thing with no user intervention. Will switch to https in most cases and fall back to http when something goes wrong. Tests cleared .  Feel free to use any code in there towards the final solution.
