### ISSUE TITLE
If chunk option 'eval' is set to a variable, checkpoint fails

### ISSUE THREAD

**Issue by renlund** [RevolutionAnalytics/checkpoint#195]
A .rnw-file like this (call it "test.rnw") :

    \documentclass{article}
    \begin{document}
    <<foo, cache = FALSE>>=
    library(knitr)
    x <- FALSE
    @

    <<bar, eval = x>>=
    1+1
    @
    \end{document}

is fine for `knitr::knit("test.rnw")`. (In the "foo"-chunk a variable `x` is defined to determine wether the "bar"-chunk should be evaluated.) However, `checkpoint::checkpoint("test.rnw")` fails since it is unable to parse this file - which I assume is due to `utils::Stangle("test.rnw")` also failing. 

Would it be perhaps be possible to get the option to use `knitr::purl` for parsing  the .rnw files instead? `knitr::purl("test.rnw")` does produce an output.

**Comment by andrie** [comment]
I confirm this is reproducible

**Comment by andrie** [comment]
Initial analysis indicates that it would be viable to use `knitr()` to parse `Rnw` files instead of `SWeave()`

**Comment by andrie** [comment]
The new version contains better error handling when using `SWeave()` - still the default.

In addition, you can now use the argument `scan.rnw.with.knitr` to force `checkpoint()` to use `knitr::knit()` to scan `.Rnw` files.

**Comment by renlund** [comment]
That sounds excellent. Thank you.
