### ISSUE TITLE
support for packages at Github?

### ISSUE THREAD

**Issue by paternogbc** [RevolutionAnalytics/checkpoint#203]
Hi,
How checkpoint deals with packages instaled from Github dev versions or packages that are not in CRAN yet?

thanks in advance.

**Comment by andrie** [comment]
Checkpoint has no inherent support for either packages on github or non-CRAN repositories.

Checkpoint makes a very simple trade-off between simplicity (ease of use) and flexibility. It's simple to use, but restricted to CRAN packages as they existed on a specific date.

If you want more flexibility, you'll have to do more work yourself, e.g. by installing github pakages from a specific tag or commit.  Alternatively, use other systems like `packrat` or `GRANbase`

**Comment by paternogbc** [comment]
Ok, thanks!
