### ISSUE TITLE
Expose project scanning functions

### ISSUE THREAD

**Issue by noamross** [RevolutionAnalytics/checkpoint#208]
There are some other situations where it's useful to extract a list of packages called in a script or project. One could write a new function for this, but as you already have it implemented (presumably with some robustness to edge cases, etc.), it would be helpful to expose this.  Something like `get_packages(file/dir)` which returns a character vector.

**Comment by andrie** [comment]
Nice suggestion!

You can access the function like this:

```R
checkpoint:::projectScanPackages()
```

Signature:

```r
> args(projectScanPackages)
function (project = getwd(), verbose = TRUE, use.knitr = FALSE, 
    auto.install.knitr = FALSE, scan.rnw.with.knitr = FALSE)
```

**Comment by andrie** [comment]
The function is `scanForPackages()`:

```r
scanForPackages <- function(project = getwd(), verbose = TRUE, 
                            use.knitr = FALSE, 
                            auto.install.knitr = FALSE, 
                            scan.rnw.with.knitr = FALSE
                          )
```
