### ISSUE TITLE
Track snapshot use and remove unused snapshots

### ISSUE THREAD

**Issue by stefanfritsch** [RevolutionAnalytics/checkpoint#209]
Hi,

I don't think there is a FR for something like this atm. The .checkpoint folder can grow quite large and has to be cleaned up by hand currently (afaik?). 

If checkpoint put a simple `.lastaccessed` file in each snapshot and updated that every time checkpoint was set to the respective snapshot then it would be trivial to write a function that removed all snapshots that are older than a certain date:

``` R
remove_not_used(since = "2015-01-01")
remove_not_used(in = ddays(90))
```

That is also something e.g. RRO could put in .Rprofile.

Thx
Stefan

**Comment by andrie** [comment]
Very nice suggestion!  Thank you.

**Comment by andrie** [comment]
I have implemented as follows:

```r
checkpointRemove(snapshotDate, checkpointLocation = "~/",
  allSinceSnapshot = FALSE, allUntilSnapshot = FALSE,
  notUsedSince = FALSE, days)
```

Right now this is only in the `dev` branch.

@stefanfritsch Can you please test and provide feedback?

**Comment by andrie** [comment]
This feature is now available in the master branch on github.

**Comment by stefanfritsch** [comment]
Sorry, I was unavailable for a while. I'm now on a project where we do work with checkpoint and I'll report any issues I might encounter.

Thanks a lot for the features, they're great.
