### ISSUE TITLE
Need to know how much data `checkpoint` downloads

### ISSUE THREAD

**Issue by ikashnitsky** [RevolutionAnalytics/checkpoint#212]
Unlike `utils::install.packages`, `checkpoint` doesn't report the amount of data downloaded in the process. Is it possible to add this information to the final report of the `checkpoint::checkpoint` call in the prompt?
***
Meanwhile, please consider answering [my SO question](http://stackoverflow.com/questions/35975404/measuring-the-amount-of-data-downloaded-during-a-session) on the matter.

**Comment by andrie** [comment]
I'm creating an experimental branch to write log data to a file.

**Comment by andrie** [comment]
The experimental branch that contains this code is `212-log-data-usage`

https://github.com/RevolutionAnalytics/checkpoint/tree/212-log-data-usage

**Comment by andrie** [comment]
This feature is now available in the dev branch. No output is shown directly by the `checkpoint()` function, but the data is available as a log file at `~/.checkpoint/checkpoint_log.csv`

**Comment by ikashnitsky** [comment]
Great!
it's nice to inform people, how much they are going to download in order to reproduce the code
