### ISSUE TITLE
Error in install.packages : Updating loaded packages

### ISSUE THREAD

**Issue by DheerajAgarwal** [RevolutionAnalytics/checkpoint#213]
This defect is similar to issue #108. I have recently upgraded to the very secure dishes and when i try to update packages, i get the error. Then it re-starts the session however the next line is broken. Even if I complete the broken line, it re-starts R session.

I have already tried uninstalling and installing R, rStudio and Rtools.

![image](https://cloud.githubusercontent.com/assets/12992001/14478689/04d7ee52-00e6-11e6-9506-68efe6980a9e.png)

**Comment by andrie** [comment]
Are using `checkpoint` in your script?

It is not clear from your question.

Does this happen in Rgui or RTerm?

**Comment by DheerajAgarwal** [comment]
I am not using check point. I was updating to latest in RStudio using the update in the `file, plot...` pane. See screenshot

![image](https://cloud.githubusercontent.com/assets/12992001/14494360/9449f2ac-0158-11e6-9385-558ea5611008.png)

Please note the issue does not occur if I write the command on the R console. The issue happens only if I try to update using the Gui function as shown above.

**Comment by andrie** [comment]
I'm sorry, but in that case your question is off-topic.
