### ISSUE TITLE
Checkpoint doesn't appear to work with knitr and rmarkdown 

### ISSUE THREAD

**Issue by andrewjohnlowe** [RevolutionAnalytics/checkpoint#216]
Hello,

Here's what I want to do:
- I want to write my reproducible document as a _single_ R Markdown (.Rmd) file. I do not want to have to bundle a bunch of other files with my .Rmd file. I want one .Rmd file, which I can submit to a journal or give to a colleague, and they can run it and get the document. Extra files means extra complication. I would like to avoid the possibility of a reviewer or colleague not being able to generate my paper because he forgot to download some extra file. I don't want to package everything in a project as a zip file or something like that; I want a single file that is human-readable, as R markdown intends. It's OK if the .Rmd generates scripts that are then used to produce the final document. And I would like to use R packages of a specific date. Can checkpoint do this?

I've read the README, specifically the section "Using knitr and rmarkdown with checkpoint" and have not been able to achieve my goal. My .Rmd file looks like this:

---

title: "Test file"
author: "Me"
date: "today"
output:
  html_document:
    highlight: kate
    keep_md: yes
##     theme: default

``` r
library(rmarkdown) # Do I need this? The documentation seems to suggest so...
```

``` r checkpoint
# Use package and R versions of this date:
library(checkpoint)
checkpoint("2016-05-04",
           R.version = "3.2.5", verbose = TRUE)
```

``` r
library(ggplot2)
# Do more stuff...
```

And the result is:

> rmarkdown::render("test.Rmd")

processing file: test.Rmd
  |...........                                                      |  17%
  ordinary text without R code

  |......................                                           |  33%
label: unnamed-chunk-1
  |................................                                 |  50%
  ordinary text without R code

  |...........................................                      |  67%
label: checkpoint
  |......................................................           |  83%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-2
Quitting from lines 24-26 (test.Rmd) 
Error in library(ggplot2) : there is no package called 'ggplot2'

The generated .md file looks like this:

```
## - Discovered 0 packages
```

```
## Unable to parse 1 files:
```

```
## - test.Rmd
```

```
## No packages found to install
```

```
## checkpoint process complete
```

```
## ---
```

``` r
library(ggplot2)
```

```
## Error in library(ggplot2): there is no package called 'ggplot2'
```

So it's pretty clear that, for some reason, checkpoint isn't parsing the .Rmd, so no packages get installed, so the checkpoint version of ggplot2 isn't found.

If I comment out the code chunk "checkpoint", then ggplot2 is found, but it's not the version from the checkpoint date. So checkpoint doesn't seem to be working for me. Or, at least, I don't know what the recipe is to get it to work as intended. I do not know how to proceed.

Please, would it be possible to post a complete worked example, with all steps explicitly stated, showing the use of checkpoint with knitr and R markdown? I think the README would benefit from including this.

With many thanks,

Andrew.

**Comment by andrie** [comment]
Hi, Andrew

I don't think we ever had this use case in mind, so it probably isn't possible right now.

The solution that should work is the solution you don't want, i.e. distribute two files:
* The `rmd`
* The R file that calls `checkpoint()` and renders the `rmd`

(Pull requests for changing this behavior are, of course, welcome!)

Andrie

**Comment by andrewjohnlowe** [comment]
Hello Andrie,

Thanks for your prompt reply! It's also reassuring to know that I hadn't made a mistake, but that instead I was trying to do something that wasn't originally intended with the software. 

I did try writing a code chunk in an Rmd that would auto-generate the R file and source it, and this would render the rest of the Rmd, but the logic became so twisty that I gave up. This is what I have so far (warning: horrible hackish):

```{r}
checkpoint.date <- "2016-05-04"

# Load library that enables us to determine the name of this .Rmd file:
if(!require(kimisc, quietly = TRUE)) { 
  install.packages("kimisc", repos = "http://cran.r-project.org")
  require(kimisc)
}
this.file <- thisfile() # The name of this R Markdown file
suffix <- sprintf("-%s.R", round(runif(1,0,1e15)))
script.file <- gsub(".Rmd", suffix, this.file) # The name of the R script

if(!file.exists(script.file)) {
  line1 <- "require(checkpoint, quietly = TRUE)\n"
  line2 <- sprintf("checkpoint(\'%s\')\n",checkpoint.date)
  line3 <- sprintf("rmarkdown::render(\'%s\')\n", this.file)
  cat(line1, line2, line3, file = script.file)
  print(script.file)
#source(script.file)
#file.remove(script.file)
knitr::knit_exit()
} 
# Proceed...
```

Problem is, when the auto-generated R script is sourced, knitr isn't found, so rendering can't happen:

> require(checkpoint, quietly = TRUE)

>  checkpoint('2016-05-04')
Scanning for packages used in this project
  |===============================================================================| 100%
- Discovered 3 packages
Installing packages used in this project 
 - Installing ‘knitr’
also installing the dependencies ‘evaluate’, ‘stringr’

checkpoint process complete
---

>  rmarkdown::render('test.Rmd')
Error in utils::packageVersion("knitr") : package ‘knitr’ not found
In addition: Warning messages:
1: In projectScanPackages(project, use.knitr = use.knitr, scan.rnw.with.knitr = scan.rnw.with.knitr) :
  rmarkdown files found and will not be parsed. Set use.knitr = TRUE
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘knitr’

The output above claims that knitr gets installed, but then later it's not found. Eh?! So I have no idea how to proceed. Pity, because the next stage was to tweak the code chunk above so that it would bale out and not infinitely recurse. Maybe you make use of it somehow.

Best regards,

Andrew.

**Comment by ignacio82** [comment]
Any update about using checkpoint with rmarkdown and r notebooks? I was also trying to do this and failed :(

**Comment by JeffreyRacine** [comment]
Greetings,

After some tweaking I was able to get these working harmoniously. Hopefully the following is replicable (my students report it is).

To incorporate `checkpoint()` in your R Markdown file, create an R code chunk in which you first load all R packages used in your Markdown script, followed by the `checkpoint` and `codetools` packages (you must install these first). The following R code chunk loads all required packages (for this script, `fpp` followed by `checkpoint` and `codetools`), then creates a hidden checkpoint directory named `.checkpoint` in the current working directory, then checkpoints for a specific date. This code should precede code chunks that make use of the required libraries (in this script, `fpp`). The first time you compile your R Markdown script this will install all libraries in the local checkpoint directory (this may take a minute or two). Make sure you set the working directory to the directory where your Markdown script resides (in RStudio, from the menu select `Session -> Set Working Directory -> To Source File Location`).

    ```{r,include=FALSE}`r ''`
    require(fpp)
    require(checkpoint)
    require(codetools)
    dir.create(".checkpoint")
    checkpoint("2017-01-01",R.version="3.3.2",checkpointLocation=getwd())
    ```

Now your R Markdown script is checkpointed, and furthermore if you execute the R command `knitr::purl("foo.Rmd")` in a separate R session where `foo.Rmd` is the name of your R Markdown script, this will strip off only the R code associated with your project, but with the checkpoint facility intact, and write just the R code to a file named `foo.R`. Now all you need to do is to circulate the file `foo.R` along with any supporting data files.

**Comment by andrie** [comment]
@JeffreyRacine 

Thank you very much for posting this set of instructions for resolving this problem.

I haven't tried your suggestion yet (will do this in due course). This looks perfectly sensible, although I find it puzzling that `codetools` should be required explicitly.  If this is really necessary, I don't understand why.

Andrie

**Comment by JeffreyRacine** [comment]
Hi Andrie,

Most welcome. re: code tools... as you surmise, it is not needed. At some point when I was trying to get this to work I got the message `codetools not installed` and included it. I just removed it and started from scratch and .checkpoint was created and used, so the process is even a bit simpler.

Thanks again!

Jeff

**Comment by JeffreyRacine** [comment]
Update - for some reason, creating a PDF document fails without codetools (HTML works)... perhaps we need to incorporate it to support various output formats?

**Comment by andrie** [comment]
I have not been able to replicate this. As far as I can tell, this code loads the packages into the workspace prior to calling `checkpoint()` but then fails to actually install these packages into the `.checkpoint` folder.

Thus `checkpoint()` has no effect at all.

I have a hackish way of using `checkpoint()` inside a markdown file and will write this up as a vignette (coming soon).

**Comment by JeffreyRacine** [comment]
Works for me, creates the dir etc. Perhaps see the working example at

https://socserv.mcmaster.ca/racinej/762/bookdown_masterclass.html

ls .checkpoint/
total 8
drwxr-xr-x  4 jracine  staff   136B 24 Feb 06:46 2017-02-04
drwxr-xr-x  3 jracine  staff   102B 23 Feb 14:25 R-3.3.2
-rw-r--r--  1 jracine  staff   1.9K 23 Feb 14:29 checkpoint_log.csv

ls .checkpoint/2017-02-04/lib/x86_64-apple-darwin16.1.0/3.3.2/
total 0
drwxr-xr-x  15 jracine  staff   510B 23 Feb 14:27 MASS
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 RColorBrewer
drwxr-xr-x  23 jracine  staff   782B 23 Feb 14:27 Rcpp
drwxr-xr-x  18 jracine  staff   612B 23 Feb 14:28 RcppArmadillo
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 assertthat
drwxr-xr-x   9 jracine  staff   306B 23 Feb 14:25 codetools
drwxr-xr-x  16 jracine  staff   544B 23 Feb 14:27 colorspace
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 dichromat
drwxr-xr-x  13 jracine  staff   442B 23 Feb 14:27 digest
drwxr-xr-x  11 jracine  staff   374B 23 Feb 14:29 evaluate
drwxr-xr-x   9 jracine  staff   306B 23 Feb 14:29 expsmooth
drwxr-xr-x   9 jracine  staff   306B 23 Feb 14:29 fma
drwxr-xr-x  12 jracine  staff   408B 23 Feb 14:29 forecast
drwxr-xr-x   9 jracine  staff   306B 23 Feb 14:29 fpp
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 fracdiff
drwxr-xr-x  14 jracine  staff   476B 23 Feb 14:28 ggplot2
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 gtable
drwxr-xr-x  11 jracine  staff   374B 23 Feb 14:29 highr
drwxr-xr-x  19 jracine  staff   646B 23 Feb 14:29 knitr
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 labeling
drwxr-xr-x  15 jracine  staff   510B 23 Feb 14:27 lattice
drwxr-xr-x  12 jracine  staff   408B 23 Feb 14:27 lazyeval
drwxr-xr-x  14 jracine  staff   476B 23 Feb 14:28 lmtest
drwxr-xr-x  11 jracine  staff   374B 23 Feb 14:27 magrittr
drwxr-xr-x  17 jracine  staff   578B 23 Feb 14:29 markdown
drwxr-xr-x  11 jracine  staff   374B 23 Feb 14:29 mime
drwxr-xr-x  12 jracine  staff   408B 23 Feb 14:27 munsell
drwxr-xr-x  13 jracine  staff   442B 23 Feb 14:27 nnet
drwxr-xr-x  13 jracine  staff   442B 23 Feb 14:27 plyr
drwxr-xr-x  10 jracine  staff   340B 23 Feb 14:27 quadprog
drwxr-xr-x  13 jracine  staff   442B 23 Feb 14:28 reshape2
drwxr-xr-x  12 jracine  staff   408B 23 Feb 14:28 scales
drwxr-xr-x   3 jracine  staff   102B 23 Feb 14:25 src
drwxr-xr-x  15 jracine  staff   510B 23 Feb 14:27 stringi
drwxr-xr-x  13 jracine  staff   442B 23 Feb 14:27 stringr
drwxr-xr-x  13 jracine  staff   442B 23 Feb 14:27 tibble
drwxr-xr-x  11 jracine  staff   374B 23 Feb 14:27 timeDate
drwxr-xr-x  12 jracine  staff   408B 23 Feb 14:28 tseries
drwxr-xr-x  15 jracine  staff   510B 23 Feb 14:29 yaml
drwxr-xr-x  18 jracine  staff   612B 23 Feb 14:27 zoo

**Comment by andrie** [comment]
Hmmm. Interesting, I can't replicate your document.  I downloaded the .Rmd, put it into an empty folder, installed the packages, then tried to knit. I get:

```
30%
  ordinary text without R code

  |.......................                                          |  35%
label: tabname (with options) 
List of 1
 $ echo: logi FALSE

Quitting from lines 337-338 (energy.Rmd) 
Error in loadNamespace(name) : there is no package called 'highr'
```

PS. Amazing document!!!

**Comment by JeffreyRacine** [comment]
Thanks... 

Try installing highr and download the screenshot and bibtex file (or zip that has it all)...

**Comment by andrie** [comment]
I could not get this suggestion to work, but this inspired a modified solution, now available as a vignette:

http://htmlpreview.github.io/?https://github.com/RevolutionAnalytics/checkpoint/blob/master/vignettes/using-checkpoint-with-knitr.html

**Comment by JeffreyRacine** [comment]
Great,

I will take a look and make sure things are getting loaded, but I am 99.% sure they are (the overhead associated with checkpointing is significant and when disabled noticeable).

Jef

**Comment by andrie** [comment]
Closing this issue, since I explain in the vignette how to do this.
