### ISSUE TITLE
New packages not available?

### ISSUE THREAD

**Issue by JWiley** [RevolutionAnalytics/checkpoint#221]
I was trying to install a new package, but it keeps saying it is not available, even though when I check, it seems to be available.  I ran the below from a clean vanilla start of MRO 3.3.1.

```r
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Microsoft R Open 3.3.1
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing(using 2 cores).

Default CRAN mirror snapshot taken on 2016-07-01. See: https://mran.microsoft.com/.
> library(checkpoint)

checkpoint: Part of the Reproducible R Toolkit from Microsoft
https://mran.microsoft.com/documents/rro/reproducibility/
> checkpoint("2016-08-26", scanForPackages=FALSE)
checkpoint process complete
---
> install.packages("JWileymisc")
Installing package into 'C:/Users/jwile/.checkpoint/2016-08-26/lib/x86_64-w64-mingw32/3.3.1'
(as 'lib' is unspecified)
Warning message:
package 'JWileymisc' is not available (for R version 3.3.1)
>
```

Okay, so R thinks it is not available from that checkpoint date, but when I look at the CRAN time machine...

![image](https://cloud.githubusercontent.com/assets/322716/18037671/4ec1cbe2-6dcd-11e6-8fce-eae0481a2319.png)

**Comment by andrie** [comment]
You are confusing some concepts:
* The static snapshot refers to the fact that MRO sets your snapshot data, i.e. it changes `options(repos)` to a date in the past.
* The checkpoint package doesn't change the `repos` setting when you invoke `checkpoint()`
* Thus, when you use `install.packages()`, you are still installing from the static snapshot date.

You should either:
* Use `checkpoint()` which will automatically install the package from the snapshot date into a clean environment, OR
* Change your `options(repos = ...)`, OR
* Use `install.packages(pkg, repos = "your favourite CRAN mirror)
