### ISSUE TITLE
Use checkpoint and/or a MRAN snapshot as CRAN mirror with Travis-CI

### ISSUE THREAD

**Issue by benmarwick** [RevolutionAnalytics/checkpoint#222]
I'd like to use the [checkpoint package](https://cran.r-project.org/web/packages/checkpoint/index.html) or the [MRAN snapshot repo](https://mran.revolutionanalytics.com/documents/rro/reproducibility/#snapshots) to set the versions of packages that get used when my package is built on Travis-CI.

I'm looking for advice on getting either of these working:
1. Travis using the local files (i.e. stored in the github repo of my pkg) of the packages that my package depends on. For example, if I use checkpoint to download the sources of the packages and store them in a directory with my package, how can I get Travis to install the packages from that local location, rather than from CRAN? or,
2. Travis use the MRAN snapshot URL to download the packages archived on a specific date, as set in the URL. 

I've been experimenting with various options in the .travis.yml file in this test package: https://github.com/benmarwick/checkpointtest

For example, here are .travis.yml files that I've tried:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

cran: https://mran.revolutionanalytics.com/
```

and

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

repos:
  CRAN: https://mran.revolutionanalytics.com/snapshot/2016-09-02
```

and

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
cran: https://mran.revolutionanalytics.com/snapshot/2016-09-02
env:
  global:
  - R_LIBS_USER=~/vignettes/packages/.checkpoint/2016-09-02/lib/x86_64-w64-mingw32/3.3.1
  - R_LIBS_SITE=~/vignettes/packages/.checkpoint/2016-09-02/lib/x86_64-w64-mingw32/3.3.1
```

And several other combinations. 

So far everything has resulted in an error (https://travis-ci.org/benmarwick/checkpointtest), often this is the error message:

```
W: Failed to fetch https://mran.revolutionanalytics.com//bin/linux/ubuntu/precise/Packages server certificate verification failed.
 CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

How can I get Travis-CI to be aware of the checkpoint package, and not contact CRAN to download dependencies? 

I've cross-posted this at the [microsoft forums](https://social.technet.microsoft.com/Forums/en-US/90e4998e-463d-4766-9f96-a6133ebbb623/how-to-use-checkpoint-and-a-mran-snapshot-as-cran-mirror-with-travisci?forum=ropen#90e4998e-463d-4766-9f96-a6133ebbb623) and [SO](http://stackoverflow.com/questions/39312260/use-checkpoint-and-a-mran-snapshot-as-cran-mirror-with-travis-ci)

**Comment by sfweller** [comment]
Hi Ben,

The error message indicates that the issue/problem is that your local machine does not trust the certificate it is being issued. Their are a few commands you can use to check and verify the connection to the MRAN server.

For a list of suggestions, I would check the following post:
http://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c

Also, can you please tell us the exact command you ran that resulted in the below error?

W: Failed to fetch 
https://mran.revolutionanalytics.com//bin/linux/ubuntu/precise/Packages
server certificate verification failed.
CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

I do notice that in the error the MRAN URL path contains two forward slashes in it, which doesn't seem right to me.  Looking at the code in the 'checkpointtest' project in the URL you provided I do not see where you are pointing it to the MRAN repository.

Stephen Weller
Microsoft R Product Team

**Comment by benmarwick** [comment]
Hi Stephen,

Thanks for taking a look. The code is run on a remote continuous integration service (Travis-CI), so the output I quote above is not my local machine. You can see the logs of my experiments with this service here: https://travis-ci.org/benmarwick/checkpointtest/builds

I'm trying a different approach now, where the Travis-CI machine runs `checkpoint()` before loading and testing my package. The entire code that I'm using is this:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: false
install:
 - mkdir $HOME/.checkpoint
 - R -e "install.packages(c('devtools', 'checkpoint', 'rmarkdown', 'knitr', 'testthat'), repos = 'http://cran.revolutionanalytics.com'); devtools::install_github('benmarwick/checkpointtest'); library(knitr); checkpoint::checkpoint('2015-01-10',  auto.install.knitr = TRUE, use.knitr = TRUE)"
```

The main problem I am encountering is that `checkpoint` is not scanning my Rmd file to detect packages (from https://travis-ci.org/benmarwick/checkpointtest/builds/160521975#L1938):

```
Scanning for packages used in this project
- Discovered 2 packages
Unable to parse 2 files:
- Readme.Rmd
- vignettes/checkpointtest.Rmd
```

Any thoughts on how I can get checkpoint working on Travis-CI?
Thanks!

**Comment by andrie** [comment]
I notice you use `cache: packages` in all these configurations. This installs packages from a binary cache, and not CRAN.  Have you tried without using cache?

**Comment by andrie** [comment]
I notice you use `cache: packages` in all these configurations. This installs packages from a binary cache, and not CRAN.  Have you tried without using cache?
