### ISSUE TITLE
expose argument for 'attempt to install these from sources'

### ISSUE THREAD

**Issue by benmarwick** [RevolutionAnalytics/checkpoint#223]
When using checkpoint I often get messages like this:

```
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: �MASS�
Do you want to attempt to install these from sources?
y/n: 
```

Which requires me to respond several times during the process. 

Can we have an argument like  `install.sources = TRUE` to make this non-interactive? 

For example:

```
checkpoint("2015-01-10", 
           auto.install.knitr = TRUE,
           use.knitr = TRUE, 
           checkpointLocation = "../packages",
            install.sources = TRUE)
```

**Comment by andrie** [comment]
Reading the help for `?install.packages`, in the section "Binary packages", I find:

>> The action if there are source packages which are preferred but may contain code which needs to be compiled is controlled by `getOption("install.packages.compile.from.source")`.  `type = "both"` will be silently changed to `"binary"` if either `contriburl` or `available` is specified.

Please try the following in your session, prior to running `checkpoint()`:

```r
options(install.packages.compile.from.source = "both")
```

That may be all you have to do.  Right now, it seems overkill to add this to as an argument to the package, but am open to pull requests that includes this functionality.

**Comment by andrie** [comment]
v0.4.1 will set `options()` for the duration of the `checkpoint()` call to install from `both`.

**Comment by andrie** [comment]
I take that back.  My experiments with including this functionality directly in `checkpoint()` were unsuccessful.
