### ISSUE TITLE
Emacs org mode files (enhancement request)

### ISSUE THREAD

**Issue by andreaskiermeier** [RevolutionAnalytics/checkpoint#232]
I'd like to use checkpoint, but don't always use the standard files (e.g. .R or .Rnw). Instead I use org-mode in emacs for reproducible research. Unfortunately, _projectScanPackages_ doesn't look at ".org" files.
Thanks.

**Comment by andrie** [comment]
Please describe what an `.org` file is, and how you want this this file to be parsed.

**Comment by andreaskiermeier** [comment]
Hi Andrie,
the org mode files are plain text files, not dissimilar to Sweave files. I think the key is that all R code is located in "code blocks" which are of the format:
```
#+BEGIN_SRC R :arguments
 Some R code
#+END_SRC
```
where arguments determine what happens to the results of the block, e.g. printing, saving, etc.
So I would have library calls inside such code blocks, not unlike Sweave files.
Let me know if this isn't clear or you need more info.
Thanks.

**Comment by andrie** [comment]
So, according to your description a `.org` file is exactly like a `.R` file. Some lines have comments, and some lines contain R code.

In that case, if you rename the file to `.R`, do you get the functionality you need?

If not, please specify the file more precisely, and propose a mechanism how to parse such a file using R.

**Comment by andreaskiermeier** [comment]
Hi Andrie,
its more like a sweave file than an R file. Your approach works, but is a bit cumbersome, as you have to remember to tangle the file to extract the R code (if additional packages are being used). Hence my request to include ".org" files in the list of files that projectScanPackages() looks in. 
Thanks.

**Comment by andrie** [comment]
It's unclear what you are asking.

Please provide:

* Detailed description of an org file
* Example files
* Detailed description of the parsing process
* Unit test cases

Or better, provide a pull request with your desired functionality.

**Comment by andreaskiermeier** [comment]
Hi Andrie,
I have attached a simple org file, which is probably a bit more involved than absolutely needs to be, but it does show you the overall format. Anything line starting with "#+" has settings for org-mode. I've also included the R file that was produced by tangling this file.
Other than that I can really only point you towards the org-mode help, but I don't expect you to learn all about org-mode.
What do you mean with "a detailed description of the parsing process" - isn't this basically the same as for R or Rnw files, where you're looking for "library()" and "require()" calls.
I also tangled an org mode file which contains library calls for packages: checkpoint, tidyverse, mc2d, and fitdistrplus, to produce the pure R code. Subsequently running checkpoint in that project folder resulted in with the following output and error:
```
> checkpoint("2017-01-31")
Scanning for packages used in this project
  |====================================================================================================| 100%
- Discovered 3 packages
Installing packages used in this project 
 - Installing 'mc2d'
package 'mvtnorm' successfully unpacked and MD5 sums checked
package 'mc2d' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\andre\AppData\Local\Temp\RtmpwX2UYb\downloaded_packages
 - Installing 'tidyverse'
package 'colorspace' successfully unpacked and MD5 sums checked
package 'mnormt' successfully unpacked and MD5 sums checked
package 'foreign' successfully unpacked and MD5 sums checked
package 'dichromat' successfully unpacked and MD5 sums checked
package 'munsell' successfully unpacked and MD5 sums checked
package 'labeling' successfully unpacked and MD5 sums checked
package 'plyr' successfully unpacked and MD5 sums checked
package 'psych' successfully unpacked and MD5 sums checked
package 'reshape2' successfully unpacked and MD5 sums checked
package 'nlme' successfully unpacked and MD5 sums checked
package 'assertthat' successfully unpacked and MD5 sums checked
package 'R6' successfully unpacked and MD5 sums checked
package 'Rcpp' successfully unpacked and MD5 sums checked
package 'lazyeval' successfully unpacked and MD5 sums checked
package 'DBI' successfully unpacked and MD5 sums checked
package 'BH' successfully unpacked and MD5 sums checked
package 'digest' successfully unpacked and MD5 sums checked
package 'gtable' successfully unpacked and MD5 sums checked
package 'MASS' successfully unpacked and MD5 sums checked
package 'mime' successfully unpacked and MD5 sums checked
package 'curl' successfully unpacked and MD5 sums checked
package 'openssl' successfully unpacked and MD5 sums checked
package 'stringi' successfully unpacked and MD5 sums checked
package 'selectr' successfully unpacked and MD5 sums checked
package 'broom' successfully unpacked and MD5 sums checked
package 'forcats' successfully unpacked and MD5 sums checked
package 'haven' successfully unpacked and MD5 sums checked
package 'httr' successfully unpacked and MD5 sums checked
package 'hms' successfully unpacked and MD5 sums checked
package 'jsonlite' successfully unpacked and MD5 sums checked
package 'lubridate' successfully unpacked and MD5 sums checked
package 'magrittr' successfully unpacked and MD5 sums checked
package 'modelr' successfully unpacked and MD5 sums checked
package 'readxl' successfully unpacked and MD5 sums checked
package 'stringr' successfully unpacked and MD5 sums checked
package 'rvest' successfully unpacked and MD5 sums checked
package 'xml2' successfully unpacked and MD5 sums checked
package 'tidyverse' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\andre\AppData\Local\Temp\RtmpwX2UYb\downloaded_packages
Error in data.frame(timestamp = Sys.time(), snapshotDate = snapshotDate,  : 
  arguments imply differing number of rows: 1, 47, 38
```
So, it appears the alternative option (of tangling to R code) doesn't quite seem to work.
Thanks.

**Comment by andrie** [comment]
This request is unclear to me.

If you want to submit a pull request, please go ahead.
