### ISSUE TITLE
Add an easy way to turn off checkpoint

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#247]
For those who wish to revert to default R behavior after using checkpoint (or when using Microsoft R and its default MRAN snapshot) make it easy to revert to CRAN R settings:

* Set `options("repos")` to a standard CRAN repos (suggested: `https:\\cran.microsoft.com\`)
* Set `.libPaths` back to the default global user library

Could either add a new `uncheckpoint()` function, or make this the behaviour of `checkpoint()` (with no arguments), which currently returns an error.

**Comment by andrie** [comment]
I'm pretty sure this functionality exists and I'd documented in package help as well as vignettes, and I think the function I'd called uncheckpoint().
