### ISSUE TITLE
Unable to parse empty parameter

### ISSUE THREAD

**Issue by steve-s** [RevolutionAnalytics/checkpoint#248]
For example:

```
x <- iris[10:30,]
x <- iris[,-4]
my.func(x, y, , z)
```

It would be useful if the error message gave a line number of the first syntax error, not only the filename :-)

**Comment by Hong-Revo** [comment]
Not checkpoint related (?)

**Comment by steve-s** [comment]
yes, I assume it is an issue of the 3rd party package that you use to parse R code.
