### ISSUE TITLE
Dependencies not re-installed when forceInstall = TRUE

### ISSUE THREAD

**Issue by gosianow** [RevolutionAnalytics/checkpoint#250]
Is it possible to reinstall also all the dependencies along with a package used in a project?
I have an example where it does not work even though I set forceInstall = TRUE . I use R 3.3.0 and want a snapshot from 2016-05-04. The project folder contains only one R file with one line of code: library(ggplot2).
Here is my whole session:
```
> library(checkpoint)

checkpoint: Part of the Reproducible R Toolkit from Microsoft
https://mran.microsoft.com/documents/rro/reproducibility/
Warning message:
package ‘checkpoint’ was built under R version 3.3.2
> checkpoint("2016-05-04", forceInstall = TRUE)
Scanning for packages used in this project
- Discovered 1 packages
Removing packages to force re-install
--- Please select a CRAN mirror for use in this session ---
Fontconfig warning: ignoring UTF-8: not a valid region tag
Installing packages used in this project
 - Installing ‘ggplot2’
ggplot2
checkpoint process complete
---
> library(ggplot2)
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.5 (unknown)

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ggplot2_2.1.0    checkpoint_0.4.1

loaded via a namespace (and not attached):
[1] colorspace_1.3-2 scales_0.5.0     plyr_1.8.4       tools_3.3.0
[5] gtable_0.2.0     Rcpp_0.12.12     grid_3.3.0       munsell_0.4.3
[9] tcltk_3.3.0
```
Only the `ggplot2` package has a version from 2016-05-04. All the other dependencies, such as `Rcpp` or `scales`, have the very recent versions. Could I update them to the versions from 2016-05-04 automatically?

**Comment by Hong-Revo** [comment]
You should restart your session after creating a checkpoint, to be sure that you don't have non-checkpointed packages loaded. That said, checkpoint should install all package dependencies from the specified snapshot.
