### ISSUE TITLE
Catch 22, top level packages get installed when dependencies not available in MRAN, but then dependencies don't get installed once they are available in MRAN

### ISSUE THREAD

**Issue by mungojam** [RevolutionAnalytics/checkpoint#251]
We use a subset local MRAN repository with checkpoint 0.4.1. Let's say we have a call in our code:

```
checkpoint(checkpointLocation = "PathToOurLocalMRAN")
library(forecast)
```

We have added forecast to MRAN but forgotten to add one of its dependencies. Unlike install.packages() which installs from the lowest dependency upwards, checkpoint seems to ignore the missing dependency and install the forecast package anyway. 

That seems unfortunate, but it gets a bit worse than that. If we then add the dependency to our local MRAN and run the code above again, it doesn't try and install the dependency and just happily carries on. We then have no way to make it install the dependency without deleting the local version of the forecast package.

Not sure if the behaviour is as expected. If it is, then could we have a flag that tells it not to install packages unless the dependencies are there, or to still try to install the dependencies if they are not installed.

**Comment by mungojam** [comment]
It does have the benefit that it has forced me to look at using miniCRAN for managing our MRAN repository, which should mean I generally do have all the dependencies of a package available, though interestingly that also deploys from the top down, which means that network interruptions could lead to dependencies missing again...

**Comment by mungojam** [comment]
It does have the benefit that it has forced me to look at using miniCRAN for managing our MRAN repository, which should mean I generally do have all the dependencies of a package available, though interestingly that also deploys from the top down, which means that network interruptions could lead to dependencies missing again...

**Comment by andrie** [comment]
The `checkpoint` package uses `install.packages()` without modification, so not much we can do to change this behaviour.

However, you can use the `forceInstall` argument to:

> If TRUE, forces the re-installation of all discovered packages and their dependencies. This is useful if, for some reason, the checkpoint archive becomes corrupted.

**Comment by mungojam** [comment]
Going through the code at the moment. This looks like one potential place to fix it. It could use pkgDep to find all potential packages that may need installing and then see if they are in the repository, rather than just checking the top level package:

```
  if (length(packages.to.install) > 0) {
    setMranMirror(snapshotUrl = snapshoturl)
    not.available <- !packages.to.install %in% available.packages()[, 
      "Package"]
    if (sum(not.available > 0)) {
      mssg(verbose, "Packages not available in repository and won't be installed:")
      for (pkg in packages.to.install[not.available]) mssg(verbose, 
        " - ", pkg)
      packages.to.install <- packages.to.install[!not.available]
    }
  }
```

**Comment by mungojam** [comment]
forceInstall is useful when doing things manually, but in an automated script we don't want to be repeatedly re-installing all packages.

**Comment by Hong-Revo** [comment]
checkpoint v1.0 no longer uses `install.packages` so the missing dependency should be caught right at the start. Unfortunately it doesn't currently support local MRAN mirrors but that's a separate issue.
