### ISSUE TITLE
install.packages asks for user feedback while running checkpoint.

### ISSUE THREAD

**Issue by jarauh** [RevolutionAnalytics/checkpoint#259]
When running R interactively, there are some occasions under which `install.packages` asks for feedback.  An example is when it has to decide whether to install packages from source that need compilation.  This behaviour is controlled through `getOption("install.packages.compile.from.source", "interactive")`.

Thus, in an interactive setting, it may happen that the user is asked for input.  However, since `install.packages` is run from within `capture.output`, the user cannot see the question which she is supposed to answer.  Instead, she only reads "y/n: ".

**Comment by Hong-Revo** [comment]
This should be fixed in v1.0 of checkpoint.
