### ISSUE TITLE
Check for packages that are called with double-colon ::

### ISSUE THREAD

**Issue by chendaniely** [RevolutionAnalytics/checkpoint#260]
The current [vignette](https://cran.r-project.org/web/packages/checkpoint/vignettes/checkpoint.html) states that checkpoint looks for all instances of `library` and `require` in the code,
but functions can directly be called from libraries using `::` should this also be used as a pattern for checkpoint to load older snapshot libraries?

**Comment by andrie** [comment]
It should already do this.  Have you found an example where it does not?

**Comment by chendaniely** [comment]
I just tested it. It does do this. I guess the documentation/vignette needs to be updated.

**Comment by andrie** [comment]
I think the documentation states this already.  If you think the documentation can be improved, please submit a pull request - we welcome contributions.
