### ISSUE TITLE
hi, i would like to use a custom folder in place of ~/.checkpoint

### ISSUE THREAD

**Issue by savvaskef** [RevolutionAnalytics/checkpoint#273]
hi,
i am using checkpoint along with r.net
and after i load checkpoint package and
library i try to make a call to checkpoint function

i thought that i could get away with checkpointLocation
but it didn't seem to work!!!

Also, even if i get around the problem of setting a custom
folder i will need a way to bypass the question that appears
at the console(prompting for directory creation)

if you have any ideas for either or both solutions, plz, elaborate
best regards

**Comment by legendre6891** [comment]
`checkpoint("YYYY-MM-DD", checkpointLocation="FOLDER NAME HERE")`

For example, you could use `checkpointLocation="."`.
