### ISSUE TITLE
checkpoint-server link is broken in wiki

### ISSUE THREAD

**Issue by rnobleeddy** [RevolutionAnalytics/checkpoint#275]
In https://github.com/RevolutionAnalytics/checkpoint/wiki, section `How does MRAN work?`, the link http://projects.revolutionanalytics.com/documents/rrt/rrtpkgs/ is broken (gives a 404 page).

**Comment by cmosetick** [comment]
Looks like the link in the wiki page has been updated and this issue can be closed now.
