### ISSUE TITLE
scanForPackages() fails when run inside an RMarkdown document being knitted

### ISSUE THREAD

**Issue by connorp** [RevolutionAnalytics/checkpoint#277]
I am hoping to use `scanForPackages()` to identify all packages used to generate an RMarkdown document, within the document. When run in the console, `scanForPackages(use.knitr = TRUE)` is able to detect all the packages loaded in the `.Rmd` file. But when knitted, it returns without any packages. 

Minimal example, saved as `test.Rmd`:

```
    ---
    title: "Test Doc"
    author: "Connor P. Jackson"
    date: "7/22/2019"
    output:
      pdf_document:
        keep_md: yes
    ---

    ```{r setup}
    library(pander)
    library(checkpoint)
    ```

    ```{r citations}
    scanForPackages(use.knitr = TRUE)
    ```

```

Expected output, as generated when run in the console: 

```
$pkgs
[1] "checkpoint" "pander"    

$error
character(0)
```

But when the document is knitted, the results are:

```
## 
## [1] "test.Rmd"
```

Any ideas why this file does not work within a document being knitted?

**Comment by grssnbchr** [comment]
Without looking specifically at your problem, I suggest you have a look at my [reproducible template](https://github.com/grssnbchr/rddj-template) that uses RMarkdown. It basically uses a workaround that temporarily writes the `library(xyz)` calls into a file and then `checkpoint` reads from that file to load/install the packages.

**Comment by connorp** [comment]
That is relevant to the problem, but this issue nevertheless seems like something that should be addressed. A workaround is not a fix.

**Comment by grssnbchr** [comment]
Absolutely agree!

**Comment by Hong-Revo** [comment]
For this to work correctly, run `rmarkdown::render("yourfile.Rmd")` in the REPL.

**Comment by Hong-Revo** [comment]
Also note that fundamentally, checkpoint uses directories to define projects. This is problematic with Rmd files as:

- knitting can take place in any directory
- other files in the directory will affect what gets checkpointed (an Rmd is not self-contained)

So, best practice would be to put your Rmds in a directory of their own, and call `rmarkdown::render` with the `knit_root_dir` argument set appropriately.
