### ISSUE TITLE
--no-lock option to install.packages causes collisions

### ISSUE THREAD

**Issue by corynissen** [RevolutionAnalytics/checkpoint#279]
We have a server that spawns multiple R processes that use checkpoint. When two processes attempt to install to the same checkpoint directory at the same time, package install errors occur. 
```
 install.packages(pkgs = pkg, verbose = FALSE, 
                           quiet = FALSE,
                           INSTALL_opts = "--no-lock")
```
Are there any side effects to making this option "--no-lock" something we can disable when calling checkpoint?

**Comment by Hong-Revo** [comment]
I've added a `use.lock` flag to `checkpoint` that defaults to TRUE, which should fix this.
