### ISSUE TITLE
Create the local repository folder when scanForPackages = FALSE

### ISSUE THREAD

**Issue by vspinu** [RevolutionAnalytics/checkpoint#281]
Currently `checkpoint` fails when scanForPackages=FALSE and no local directory exists:

```R
> checkpoint::checkpoint("2019-11-01", scanForPackages = FALSE, verbose = FALSE)
Error in checkpoint::checkpoint("2019-11-01", scanForPackages = FALSE,  : 
  Local snapshot location does not exist
```

Would it make more sense to initialize the local repo instead of throwing an error? Or at least have an option to not throw an error?

**Comment by Hong-Revo** [comment]
The new behaviour in v1.0 is to create the checkpoint directory first, before scanning. You can also turn scanning off, if all you want is for the directory to be created.

**Comment by juliancabezas** [comment]
Hi, same issue here, the package throws an error if I use scanForPackages = FALSE. It would be much more useful to initialize the local repo instead, as I think the error can be confusing to users
