### ISSUE TITLE
R ML server checkpoint update not working

### ISSUE THREAD

**Issue by dominic007** [RevolutionAnalytics/checkpoint#285]
I was trying to update packages to a new checkpoint (current one is as of 2018 Jan). SO ran the following code (which I obtained after browsing hundreds of pages).

` library(checkpoint)`
`update.packages(lib.loc = .libPaths()[1])`
`example_project <- paste0("~/checkpoint_example_project_", Sys.Date())`
`dir.create(example_project, recursive = TRUE, showWarnings = FALSE)`
`checkpoint("2019-09-30",checkpointLocation = tempdir(),project =example_project)`

and got the following output;

> Scanning for packages used in this project
> Discovered 0 packages
> No packages found to install
> checkpoint process complete

What should I do to update to a more recent checkpoint? I am **not an expert in computer**, so simple explanation or step by step process would be appreciated.

**Comment by Hong-Revo** [comment]
You need to give checkpoint the directory that holds your actual R files.
