### ISSUE TITLE
MRAN server is down

### ISSUE THREAD

**Issue by AliciaXu111** [RevolutionAnalytics/checkpoint#286]
Cannot use checkpoint because the MRAN server is down.

Warning messages:
1: In httpsSupported() :
  cannot open the connection to 'https://mran.microsoft.com/snapshot'
2: In httpsSupported() :
  cannot open the connection to 'https://mran.microsoft.com/snapshot'
3: Unable to reach MRAN root at http://mran.microsoft.com/snapshot/

**Comment by jochandy** [comment]
Please retry and let us know if you still see failures.

**Comment by AliciaXu111** [comment]
It works now!
