### ISSUE TITLE
Warn if Bioconductor packages detected

### ISSUE THREAD

**Issue by Hong-Revo** [RevolutionAnalytics/checkpoint#294]
Since these aren't checkpointed by default.

**Comment by Hong-Revo** [comment]
Alternative is to treat all packages as being from CRAN, and allow BioC packages only via a checkpoint.yml file.

@revodavid your thoughts?

**Comment by revodavid** [comment]
I think that's reasonable, if we document that scanning is for CRAN packages only and all else needs to be handled directly

**Comment by Hong-Revo** [comment]
Well, the current assumption is that scanning is for CRAN only, so this wouldn't really be a change. It's more that pkgdepends' default behaviour is more permissive (it will look for packages on both CRAN and Bioconductor unless you put a restriction on it).

**Comment by Hong-Revo** [comment]
450f68f101b53f83bf2b14b275bb5ffee92b6f94
